import:
  - source: Alfresco/alfresco-build-tools:.travis.library.yml@v1.0.0
  - source: Alfresco/alfresco-build-tools:.travis.pre-commit.yml@v1.0.0
  - source: Alfresco/alfresco-process-scripts:slack_apa_channel_notification.yml@master
before_script:
  - |-
    export MAVEN_CLI_OPTS="${MAVEN_CLI_OPTS} -Ddoclint=none \
      -DaltReleaseDeploymentRepository=alfresco-public::default::https://artifacts.alfresco.com/nexus/content/groups/public \
      -DaltSnapshotDeploymentRepository=alfresco-public-snapshots::default::https://artifacts.alfresco.com/nexus/content/groups/public-snapshots"
