import:
  - source: Alfresco/alfresco-build-tools:.travis.library.yml@v1.0.0
  - source: Alfresco/alfresco-build-tools:.travis.pre-commit.yml@v1.0.0
  - source: Alfresco/alfresco-process-scripts:slack_apa_channel_notification.yml@master
