import:
  - source: Alfresco/alfresco-build-tools:.travis.java.yml@v1.1.5
  - source: Alfresco/alfresco-process-scripts:slack_apa_channel_notification.yml@master
branches:
  only:
    - release/5.0.N
before_script:
  - |-
    export MAVEN_CLI_OPTS="${MAVEN_CLI_OPTS} -Ddoclint=none \
      -DaltReleaseDeploymentRepository=alfresco-public::default::https://artifacts.alfresco.com/nexus/content/repositories/releases \
      -DaltSnapshotDeploymentRepository=alfresco-public-snapshots::default::https://artifacts.alfresco.com/nexus/content/repositories/snapshots"
install: mvn $MAVEN_CLI_OPTS install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
