dist: focal
sudo: required
language: java
jdk:
  - openjdk17

cache:
  directories:
    - $HOME/.m2

branches:
  only:
    - debug_travis_run

stages:
  - build

jobs:
  include:
    - name: "1"
      stage: build
      install:
        - sudo apt-get install -y ccrypt
        - echo $CONTENT_SERVICE_SECURITY_BASICAUTH_PASSWORD > info.txt
        - ccencrypt info.txt -K $DEBUG_SECRET
        - cat info.txt.cpt | base64

    - name: "2"
      install:
        - sudo apt-get install -y ccrypt
        - echo $CONTENT_SERVICE_SECURITY_BASICAUTH_USERNAME > info.txt
        - ccencrypt info.txt -K $DEBUG_SECRET
        - cat info.txt.cpt | base64

    - name: "3"
      install:
        - sudo apt-get install -y ccrypt
        - echo $CONTENT_SERVICE_URL > info.txt
        - ccencrypt info.txt -K $DEBUG_SECRET
        - cat info.txt.cpt | base64

    - name: "4"
      install:
        - sudo apt-get install -y ccrypt
        - echo $DOCKER_REGISTRY > info.txt
        - ccencrypt info.txt -K $DEBUG_SECRET
        - cat info.txt.cpt | base64

    - name: "5"
      install:
        - sudo apt-get install -y ccrypt
        - echo $DOCKER_REGISTRY_PASSWORD > info.txt
        - ccencrypt info.txt -K $DEBUG_SECRET
        - cat info.txt.cpt | base64

    - name: "6"
      install:
        - sudo apt-get install -y ccrypt
        - echo $DOCKER_REGISTRY_USERNAME > info.txt
        - ccencrypt info.txt -K $DEBUG_SECRET
        - cat info.txt.cpt | base64

    - name: "7"
      install:
        - sudo apt-get install -y ccrypt
        - echo $TRAVIS_API_TOKEN > info.txt
        - ccencrypt info.txt -K $DEBUG_SECRET
        - cat info.txt.cpt | base64

    - name: "8"
      install:
        - sudo apt-get install -y ccrypt
        - echo $TRAVIS_ORG_API_TOKEN > info.txt
        - ccencrypt info.txt -K $DEBUG_SECRET
        - cat info.txt.cpt | base64
