<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>4.0.6</version>
    <relativePath />
  </parent>

  <groupId>org.alfresco</groupId>
  <artifactId>alfresco-java-sdk-samples</artifactId>
  <version>7.3.3-SNAPSHOT</version>
  <packaging>pom</packaging>
  <name>Alfresco :: Java SDK :: Samples</name>
  <description>Sample application of the Java SDK</description>

  <properties>
    <org.apache.common-lang-3.version>3.20.0</org.apache.common-lang-3.version>
    <dependency.spring-security-web.version>7.0.5</dependency.spring-security-web.version>
    <activemq-client.version>6.2.5</activemq-client.version>
    <dependency.bouncycastle.version>1.84</dependency.bouncycastle.version>
    <dependency.jackson-databind.version>2.22.0</dependency.jackson-databind.version>
    <dependency.tools-jackson-databind.version>3.2.0</dependency.tools-jackson-databind.version>
  </properties>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.springframework.security</groupId>
        <artifactId>spring-security-web</artifactId>
        <version>${dependency.spring-security-web.version}</version>
      </dependency>
      <dependency>
        <groupId>org.apache.activemq</groupId>
        <artifactId>activemq-client</artifactId>
        <version>${activemq-client.version}</version>
      </dependency>
      <dependency>
        <groupId>org.bouncycastle</groupId>
        <artifactId>bcprov-jdk18on</artifactId>
        <version>${dependency.bouncycastle.version}</version>
      </dependency>
      <dependency>
        <groupId>com.fasterxml.jackson.core</groupId>
        <artifactId>jackson-databind</artifactId>
        <version>${dependency.jackson-databind.version}</version>
      </dependency>
      <dependency>
        <groupId>tools.jackson.core</groupId>
        <artifactId>jackson-databind</artifactId>
        <version>${dependency.tools-jackson-databind.version}</version>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <distributionManagement>
    <repository>
      <id>alfresco-enterprise-releases</id>
      <url>https://artifacts.alfresco.com/nexus/content/repositories/enterprise-releases</url>
    </repository>
    <snapshotRepository>
      <id>alfresco-enterprise-snapshots</id>
      <url>https://artifacts.alfresco.com/nexus/content/repositories/enterprise-snapshots</url>
    </snapshotRepository>
  </distributionManagement>

  <dependencies>
    <!--
      commons-lang3 is required here, as it does not get inherited from the parent pom, and it is directly using spring boot 4.0.3
      which is fetching commons-lang 3.17.0, while the SDK and samples need at least 3.20.0 to avoid CVE-2025-48924
    -->
    <dependency>
      <groupId>org.apache.commons</groupId>
      <artifactId>commons-lang3</artifactId>
      <version>${org.apache.common-lang-3.version}</version>
    </dependency>
  </dependencies>

  <modules>
    <module>extension-template</module>
    <module>event-api-handlers</module>
    <module>event-api-spring-integration</module>
    <module>oauth2-feign-sample</module>
  </modules>
</project>
