# This docker-compose file will spin up an ACS cluster on a local host or on a server and it requires a minimum of 12GB Memory to distribute among containers.
# Limit container memory and assign X percentage to JVM.  There are couple of ways to allocate JVM Memory for ACS Containers
# For example: 'JAVA_OPTS: "$JAVA_OPTS -XX:+PrintFlagsFinal -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"'
# See Oracle docs (https://docs.oracle.com/javase/9/gctuning/parallel-collector1.htm#JSGCT-GUID-CAB83393-3438-44ED-98F0-D15641B43C7D).
# If the container memory is not explicitly set then the flags above will set the max heap default to 1/4 of the container's memory, which may not be ideal.
# For performance tuning, assign the container memory and give a percentage of it to the JVM.

# Using version 2 as 3 does not support resource constraint options (cpu_*, mem_* limits) for non swarm mode in Compose
version: "2"

services:
  extension-template:
    image: extension-template:development
    environment:
      CONTENT_SERVICE_URL: "http://alfresco:8080"
      SPRING_ACTIVEMQ_BROKER_URL: "tcp://activemq:61616"
    build:
      context: .
    volumes:
      - /tmp:/tmp

  alfresco:
    image: quay.io/alfresco/alfresco-content-repository:7.0.0-A28
    mem_limit: 1700m
    environment:
      JAVA_TOOL_OPTIONS: "
              -Dencryption.keystore.type=JCEKS
              -Dencryption.cipherAlgorithm=DESede/CBC/PKCS5Padding
              -Dencryption.keyAlgorithm=DESede
              -Dencryption.keystore.location=/usr/local/tomcat/shared/classes/alfresco/extension/keystore/keystore
              -Dmetadata-keystore.password=mp6yc0UD9e
              -Dmetadata-keystore.aliases=metadata
              -Dmetadata-keystore.metadata.password=oKIWzVdEdA
              -Dmetadata-keystore.metadata.algorithm=DESede
              "
      JAVA_OPTS: "
              -Ddb.driver=org.postgresql.Driver
              -Ddb.username=alfresco
              -Ddb.password=alfresco
              -Ddb.url=jdbc:postgresql://postgres:5432/alfresco
              -Dsolr.host=solr6
              -Dsolr.port=8983
              -Dsolr.secureComms=none
              -Dsolr.base.url=/solr
              -Dindex.subsystem.name=solr6
              -Dshare.host=127.0.0.1
              -Dshare.port=8080
              -Dalfresco.host=localhost
              -Dalfresco.port=8080
              -Daos.baseUrlOverwrite=http://localhost:8080/alfresco/aos
              -Dmessaging.broker.url=\"failover:(nio://activemq:61616)?timeout=3000&jms.useCompression=true\"
              -Ddeployment.method=DOCKER_COMPOSE
              -Dtransform.service.enabled=true
              -Dtransform.service.url=http://transform-router:8095
              -Dsfs.url=http://shared-file-store:8099/
              -DlocalTransform.core-aio.url=http://transform-core-aio:8090/
              -Dcsrf.filter.enabled=false
              -Ddsync.service.uris=http://localhost:9090/alfresco
              -XX:MinRAMPercentage=50 -XX:MaxRAMPercentage=80
              "

  transform-router:
    mem_limit: 512m
    image: quay.io/alfresco/alfresco-transform-router:1.3.2-A2
    environment:
      JAVA_OPTS: " -XX:MinRAMPercentage=50 -XX:MaxRAMPercentage=80"
      ACTIVEMQ_URL: "nio://activemq:61616"

      CORE_AIO_URL : "http://transform-core-aio:8090"

      FILE_STORE_URL: "http://shared-file-store:8099/alfresco/api/-default-/private/sfs/versions/1/file"
    ports:
      - 8095:8095
    links:
      - activemq

  transform-core-aio:
    image: alfresco/alfresco-transform-core-aio:2.3.8
    mem_limit: 1536m
    environment:
      JAVA_OPTS: " -XX:MinRAMPercentage=50 -XX:MaxRAMPercentage=80"
      ACTIVEMQ_URL: "nio://activemq:61616"
      FILE_STORE_URL: "http://shared-file-store:8099/alfresco/api/-default-/private/sfs/versions/1/file"
    ports:
      - 8090:8090
    links:
      - activemq

  shared-file-store:
    image: alfresco/alfresco-shared-file-store:0.12.0
    mem_limit: 512m
    environment:
      JAVA_OPTS: " -XX:MinRAMPercentage=50 -XX:MaxRAMPercentage=80"
      scheduler.content.age.millis: 86400000
      scheduler.cleanup.interval: 86400000
    ports:
      - 8099:8099
    volumes:
      - shared-file-store-volume:/tmp/Alfresco/sfs

  share:
    image: quay.io/alfresco/alfresco-share:7.0.0-A17
    mem_limit: 1g
    environment:
      REPO_HOST: "alfresco"
      REPO_PORT: "8080"
      JAVA_OPTS: "
              -XX:MinRAMPercentage=50
              -XX:MaxRAMPercentage=80
              -Dalfresco.host=localhost
              -Dalfresco.port=8080
              -Dalfresco.context=alfresco
              -Dalfresco.protocol=http
              "

  postgres:
    image: postgres:13.1
    mem_limit: 512m
    environment:
      - POSTGRES_PASSWORD=alfresco
      - POSTGRES_USER=alfresco
      - POSTGRES_DB=alfresco
    command: postgres -c max_connections=300 -c log_min_messages=LOG
    ports:
      - 5432:5432

  solr6:
    image: alfresco/alfresco-search-services:2.0.1
    mem_limit: 2g
    environment:
      #Solr needs to know how to register itself with Alfresco
      - SOLR_ALFRESCO_HOST=alfresco
      - SOLR_ALFRESCO_PORT=8080
      #Alfresco needs to know how to call solr
      - SOLR_SOLR_HOST=solr6
      - SOLR_SOLR_PORT=8983
      #Create the default alfresco and archive cores
      - SOLR_CREATE_ALFRESCO_DEFAULTS=alfresco,archive
      #HTTP by default
      - ALFRESCO_SECURE_COMMS=none
    ports:
      - 8083:8983 #Browser port

  activemq:
    image: alfresco/alfresco-activemq:5.16.1
    mem_limit: 1g
    ports:
      - 8161:8161 # Web Console
      - 5672:5672 # AMQP
      - 61616:61616 # OpenWire
      - 61613:61613 # STOMP

  digital-workspace:
    image: quay.io/alfresco/alfresco-digital-workspace:2.0.0-adw
    mem_limit: 128m
    environment:
      BASE_PATH: ./

  proxy:
    image: alfresco/alfresco-acs-nginx:3.1.1
    mem_limit: 128m
    depends_on:
      - alfresco
      - digital-workspace
    ports:
      - 8080:8080
    links:
      - digital-workspace
      - alfresco
      - share

  sync-service:
    image: quay.io/alfresco/service-sync:3.4.0-M5
    mem_limit: 1g
    environment:
      JAVA_OPTS : "
          -Dsql.db.driver=org.postgresql.Driver
          -Dsql.db.url=jdbc:postgresql://postgres:5432/alfresco
          -Dsql.db.username=alfresco
          -Dsql.db.password=alfresco
          -Dmessaging.broker.host=activemq
          -Drepo.hostname=alfresco
          -Drepo.port=8080
          -Ddw.server.applicationConnectors[0].type=http
          -XX:MinRAMPercentage=50 -XX:MaxRAMPercentage=80
          "

    ports:
      - 9090:9090

volumes:
  shared-file-store-volume:
    driver_opts:
      type: tmpfs
      device: tmpfs
