spring.application.name=oauth2-feign-sample
server.port=8082

alfresco.base-url=<BASE-URL>
keycloak.auth-server-url=<IDP-URL>
keycloak.realm=alfresco
spring.security.oauth2.client.registration.alfresco-rest-api.client-id=<CLIENT-ID>
spring.security.oauth2.client.registration.alfresco-rest-api.client-secret=<CLIENT-SECRET>
spring.security.oauth2.client.registration.alfresco-rest-api.authorization-grant-type=client_credentials
spring.security.oauth2.client.registration.alfresco-rest-api.scope=openid, email
spring.security.oauth2.client.registration.alfresco-rest-api.provider=alfresco-identity-service
spring.security.oauth2.client.provider.alfresco-identity-service.token-uri=${keycloak.auth-server-url}/auth/realms/${keycloak.realm}/protocol/openid-connect/token
