name: Alfresco Java SDK CI

on:
  push:
    branches:
      - develop
      - release/**
      - dev-**
  pull_request:
    branches:
      - develop
      - release/**
      - dev-**
  workflow_dispatch:

env:
  MAVEN_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
  MAVEN_USERNAME: ${{ secrets.NEXUS_USERNAME }}
  CONTENT_SERVICE_SECURITY_BASICAUTH_PASSWORD: ${{ secrets.CONTENT_SERVICE_SECURITY_BASICAUTH_PASSWORD }}
  CONTENT_SERVICE_SECURITY_BASICAUTH_USERNAME: ${{ secrets.CONTENT_SERVICE_SECURITY_BASICAUTH_USERNAME }}
  CONTENT_SERVICE_URL: ${{ secrets.CONTENT_SERVICE_URL }}
  GITHUB_ACTIONS_DEPLOY_TIMEOUT: 60
  MAVEN_CLI_OPTS: "source:jar -B -q -e -fae -V -DinstallAtEnd=true -U -Ddoclint=none \
  -DaltReleaseDeploymentRepository=alfresco-public::default::https://artifacts.alfresco.com/nexus/content/repositories/releases \
  -DaltSnapshotDeploymentRepository=alfresco-public-snapshots::default::https://artifacts.alfresco.com/nexus/content/repositories/snapshots \
  -Denvironment.host=apadev.envalfresco.com \
  -Denvironment.apa.host=apadev-apa.envalfresco.com \
  -Denvironment.application.name=simpleapp \
  -Dags.version=14.9 -Dacs.version=7.1.0.1"

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: Alfresco/alfresco-build-tools/.github/actions/pre-commit@v1.34.2

  build_and_verify:
    name: "Build and Verify"
    runs-on: ubuntu-latest
    needs:
      - pre-commit
    steps:
      - uses: actions/checkout@v3
      - uses: Alfresco/alfresco-build-tools/.github/actions/get-build-info@v1.34.0
      - uses: Alfresco/alfresco-build-tools/.github/actions/setup-java-build@v1.34.0
      - name: "Install"
        timeout-minutes: ${{ fromJSON(env.GITHUB_ACTIONS_DEPLOY_TIMEOUT) }}
        run: mvn install ${{ env.MAVEN_CLI_OPTS }} -DskipTests=true -Dmaven.javadoc.skip=true
      - name: "Verify"
        timeout-minutes: ${{ fromJSON(env.GITHUB_ACTIONS_DEPLOY_TIMEOUT) }}
        run: mvn verify ${{ env.MAVEN_CLI_OPTS }} -Dlogging.root.level=off -Dspring.main.banner-mode=off

  publish:
    name: "Publish"
    runs-on: ubuntu-latest
    if: >
      !failure() &&
      github.event_name != 'pull_request'
    needs:
      - build_and_verify
    steps:
      - uses: actions/checkout@v3
      - uses: Alfresco/alfresco-build-tools/.github/actions/get-build-info@v1.34.0
      - uses: Alfresco/alfresco-build-tools/.github/actions/setup-java-build@v1.34.0
      - name: "Deploy"
        timeout-minutes: ${{ fromJSON(env.GITHUB_ACTIONS_DEPLOY_TIMEOUT) }}
        run: mvn deploy ${{ env.MAVEN_CLI_OPTS }} -DskipTests=true
