name: Alfresco Java SDK CI

on:
  push:
    branches:
      - release/5.0.N
  pull_request:
    branches:
      - release/5.0.N
  workflow_dispatch:

env:
  MAVEN_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
  MAVEN_USERNAME: ${{ secrets.NEXUS_USERNAME }}
  GITHUB_ACTIONS_DEPLOY_TIMEOUT: 60
  CONTENT_SERVICE_SECURITY_BASICAUTH_PASSWORD: ${{ secrets.CONTENT_SERVICE_SECURITY_BASICAUTH_PASSWORD }}
  CONTENT_SERVICE_SECURITY_BASICAUTH_USERNAME: ${{ secrets.CONTENT_SERVICE_SECURITY_BASICAUTH_USERNAME }}
  CONTENT_SERVICE_URL: ${{ secrets.CONTENT_SERVICE_URL }}
  JAVA_VERSION: 11

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: Alfresco/alfresco-build-tools/.github/actions/pre-commit@v7.0.0

  build_and_verify:
    name: "Build and Verify"
    runs-on: ubuntu-latest
    needs:
      - pre-commit
    env:
      MAVEN_CLI_OPTS: >
        source:jar -B -q -e -fae -V -DinstallAtEnd=true -U -Ddoclint=none
    steps:
      - uses: actions/checkout@v4
      - uses: Alfresco/alfresco-build-tools/.github/actions/get-build-info@v7.0.0
      - uses: Alfresco/alfresco-build-tools/.github/actions/setup-java-build@v7.0.0
        with:
          java-version: ${{ env.JAVA_VERSION }}
      - name: "Build"
        timeout-minutes: ${{ fromJSON(env.GITHUB_ACTIONS_DEPLOY_TIMEOUT) }}
        run: mvn install $MAVEN_CLI_OPTS -DskipTests=true -Dmaven.javadoc.skip=true
      - name: "Run tests"
        timeout-minutes: ${{ fromJSON(env.GITHUB_ACTIONS_DEPLOY_TIMEOUT) }}
        run: mvn verify $MAVEN_CLI_OPTS -Dlogging.root.level=off -Dspring.main.banner-mode=off

  publish:
    name: "Publish"
    runs-on: ubuntu-latest
    if: >
      github.event_name != 'pull_request'
    needs:
      - build_and_verify
    env:
      MAVEN_CLI_OPTS: >
        source:jar -B -q -e -fae -V -DinstallAtEnd=true -U -Ddoclint=none
        -DaltReleaseDeploymentRepository=alfresco-public::default::https://artifacts.alfresco.com/nexus/content/repositories/releases
        -DaltSnapshotDeploymentRepository=alfresco-public-snapshots::default::https://artifacts.alfresco.com/nexus/content/repositories/snapshots
    steps:
      - uses: actions/checkout@v4
      - uses: Alfresco/alfresco-build-tools/.github/actions/get-build-info@v7.0.0
      - uses: Alfresco/alfresco-build-tools/.github/actions/setup-java-build@v7.0.0
        with:
          java-version: ${{ env.JAVA_VERSION }}
      - name: "Publish artifacts"
        timeout-minutes: ${{ fromJSON(env.GITHUB_ACTIONS_DEPLOY_TIMEOUT) }}
        run: mvn deploy $MAVEN_CLI_OPTS -DskipTests=true
