name: Develop/Release branch workflow

on:
  push:
    branches:
      - develop
      - release/**
      - fix/**

env:
  MAVEN_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
  MAVEN_USERNAME: ${{ secrets.NEXUS_USERNAME }}
  GITHUB_ACTIONS_DEPLOY_TIMEOUT: 60
  CONTENT_SERVICE_SECURITY_BASICAUTH_PASSWORD: ${{ secrets.CONTENT_SERVICE_SECURITY_BASICAUTH_PASSWORD }}
  CONTENT_SERVICE_SECURITY_BASICAUTH_USERNAME: ${{ secrets.CONTENT_SERVICE_SECURITY_BASICAUTH_USERNAME }}
  CONTENT_SERVICE_URL: ${{ secrets.CONTENT_SERVICE_URL }}


jobs:
  run_ci:
    uses: ./.github/workflows/ci.yml
    secrets: inherit
